# Google OAuth2 Credentials
# Get these from Google Cloud Console: https://console.cloud.google.com/
GOOGLE_CLIENT_ID=182199168944-irg0mgt70mdifh3br49g91iikch0psp5.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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

# Remote Database Configuration (Optional)
REMOTE_DB_URL=jdbc:postgresql://db.miqglabqmtnqseyetwec.supabase.co:5432/postgres?user=postgres&password=KE2/sKVjF/gH$3
